### ISSUE TITLE
Log messages are too verbose

### ISSUE THREAD

**Issue by nickh4nson** [cravler/flask-twisted#1]
When GETing from my untwisted flask app the log message looks something like this
127.0.0.1 - - [2015-09-12 13:58:28] "GET /api/cases/1 HTTP/1.1" 200 2207 0.01707

With flask-twisted my log messages seem to have a lot of extra information 
2015-09-12 15:12:43-0500 [-] "127.0.0.1" - - [12/Sep/2015:20:12:42 +0000] "GET /api/cases/1 HTTP/1.1" 200 1840 "http://127.0.0.1:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"

Is there a way to configure what gets added to the message?

P.S. THANK YOU so much for this library btw it is a life saver

**Comment by cravler** [comment]
From version 0.1.1

```py
from zope.interface import provider
from twisted.web.server import Site
from twisted.web.http import _escape
from twisted.web.iweb import IAccessLogFormatter
from flask.ext.twisted import Twisted as Tx

@provider(IAccessLogFormatter)
def logFormatter(timestamp, request):
    line = (
        u'%(ip)s - - %(timestamp)s "%(method)s %(uri)s %(protocol)s" %(code)d - ' % dict(
            ip=_escape(request.getClientIP() or b"-"),
            timestamp=timestamp,
            method=_escape(request.method),
            uri=_escape(request.uri),
            protocol=_escape(request.clientproto),
            code=request.code,
        )
    )
    return line

class Twisted(Tx):
    def create_site(self, resource, **options):
        return Site(resource, logFormatter=logFormatter)

```

**Comment by nickh4nson** [comment]
@cravler  Thank you for the help!
