### ISSUE TITLE
python 3 issue?

### ISSUE THREAD

**Issue by benman1** [cravler/flask-twisted#2]
This project looks great, but I am getting this issue: 

```
 app.run(host=app.iniconfig.get('flask', 'host'), port=app.iniconfig.getint('flask', 'port'))
 File "/usr/local/lib/python3.4/dist-packages/flask_twisted/__init__.py", line 67, in run
   self.run_simple(app, host, port, **options)
 File "/usr/local/lib/python3.4/dist-packages/flask_twisted/__init__.py", line 32, in run_simple
   self.trigger('run', app)
 File "/usr/local/lib/python3.4/dist-packages/observable/core.py", line 81, in trigger
   if not event in self.events or not self.events[event]:
  AttributeError: 'Twisted' object has no attribute 'events'
```

**Comment by dustinkeib** [comment]
I'm getting this in Python 2.7.12 in a clean virtualenv with only the required dependancies as well.

**Comment by Dick-Wilder** [comment]
The problem is not specific to python 3. The issue title ought to be changed. 

The underlying problem is that in flask_twisted/__init__.py the Twisted constructor does not call it's base class (Observable) constructor . The code ought to be: 
`class Twisted(Observable):

    def __init__(self, app=None):
        super(Twisted, self).__init__() # this is the missing call to base class constructor
        ...`
@benman1 @dustinkeib

**Comment by cravler** [comment]
version 0.1.2 created
